version: '2'
services:  
  nodered:
    image: kalemena/node-red:0.17.5
    restart: always
    ports:
     - "1880:1880"
     - "1883:1883"
    volumes:
     - ./src/flow/data:/root/.node-red
    devices:
     - "/dev/ttyUSB2:/dev/ttyCurrenCost"
     - "/dev/ttyUSB0:/dev/ttyJeeLink"
     - "/dev/ttyUSB1:/dev/ttyRfxTrx"
    environment:
     - FLOWS=flows_nodered.json
     
  tidhome:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./src/web/www:/usr/share/nginx/html