version: '3.7'
services:

  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes: 
      - ./data/influxdb:/var/lib/influxdb    
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

  # chronograf:
  #   image: chronograf
  #   ports:
  #     - "8888:8888"
  #   command: "--influxdb-url=http://influxdb:8086"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
  #    - ./etc/grafana:/etc/grafana
      - ./data/grafana/var/lib/grafana:/var/lib/grafana
      - ./data/grafana/var/log/grafana:/var/log/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

  telegraf:
    image: telegraf
    restart: always
    network_mode: host    
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro      
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc

  mqtt:
    image: eclipse-mosquitto:1.4.12
    restart: always
    ports:
     - "2883:1883"
     - "9001:9001"

  nodered:
    image: kalemena/node-red:0.19.4
    restart: always
    ports:
     - "1880:1880"
     - "1883:1883"
    volumes:
     - ./src/flow/data:/root/.node-red
     - ./etc/nodered/settings.js:/home/node-red/settings.js
    devices:
     - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
     - "/dev/ttyJeeLink:/dev/ttyJeeLink"
     - "/dev/ttyRfxTrx:/dev/ttyRfxTrx"
    environment:
     - FLOWS=tidhome.json

  tidhome:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./src/web/www:/usr/share/nginx/html
