version: '2'
services:  
  nodered:
    image: kalemena/node-red:0.16.2
    restart: always
    ports:
     - "1880:1880"
     - "1883:1883"
    volumes:
     - ./src/flow/data:/root/.node-red
    devices:
     - "/dev/ttyCurrenCost:/dev/ttyCurrenCost"
     - "/dev/ttyJeeLink:/dev/ttyJeeLink"
     - "/dev/ttyRfxTrx:/dev/ttyRfxTrx"
    environment:
     - FLOWS=tidhome.json
     
  tidhome:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./src/web/www:/usr/share/nginx/html